test: account1221321

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?characterEncoding=utf8&useSSL=true
    platform: mysql
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: info
    com.yokimi: debug
    feign: debug
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
yokimi-ebusiness-cloud-finance:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
endpoints:
  shutdown:
    enabled: true
    sensitive: false