test: shop32321

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8&useSSL=true
    platform: mysql
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: info
    com.yokimi: debug


#Hystrix默认的超时时间是1秒，如果超过这个时间尚未响应，将会进入fallback代码。
#而首次请求往往会比较慢（因为Spring的懒加载机制，要实例化一些类），这个响应时间可能就大于1秒了。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
#hystrix.command.default.execution.timeout.enabled: false # 关闭超时检查
#feign.hystrix.enabled: false # 关闭hytrix

endpoints:
  shutdown:
    enabled: true
    sensitive: false